const LEVELS=['A1','A2','B1','B2','C1','C2','KIDS'],progressKey='studyProgressV1',sessionKey='studySessionV1',day=86400000;
const style=document.createElement('link');style.rel='stylesheet';style.href='css/estudo.css';document.head.append(style);
document.querySelector('#eligibleCount').textContent='1 ou mais cartões serão verificados pelos filtros.';
const $=s=>document.querySelector(s),read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let units=[],session=null;
async function load(){for(const l of LEVELS)try{units.push(...await fetch(`dados/${l.toLowerCase()}/unidades.json`).then(r=>r.json()))}catch{}for(const l of LEVELS)if(units.some(u=>u.nivel===l))$('#studyLevel').add(new Option(l,l));fillFilters();bind();renderSummary();updateEligible();const saved=read(sessionKey,null);if(saved?.queue?.length){session=saved;$('#resumeStudy').hidden=false}}
function fillFilters(){const add=(el,v)=>[...new Set(v)].sort().forEach(x=>el.add(new Option(x,x)));add($('#studyPanel'),units.flatMap(u=>u.paineis));add($('#studySubpanel'),units.map(u=>u.subpainel));add($('#studySkill'),units.map(u=>u.habilidade_principal))}
function paired(u){return u.conteudo_en?.length&&u.conteudo_en.length===u.traducoes?.length&&u.traducoes.every((x,i)=>x&&!/conteúdo integral|rótulo editorial|tradução preservada|contraste visual/i.test(x)&&u.conteudo_en[i])}
function filtered(){const p=read(progressKey,{}),now=Date.now(),fav=read('nivelState',{}).favorites||[],source=$('#studySource').value,requested=(new URLSearchParams(location.search).get('unidades')||'').split(',').filter(Boolean);return units.filter(u=>(!requested.length||requested.includes(u.id))&&(!$('#studyLevel').value||u.nivel===$('#studyLevel').value)&&(!$('#studyPanel').value||u.paineis.includes($('#studyPanel').value))&&(!$('#studySubpanel').value||u.subpainel===$('#studySubpanel').value)&&(!$('#studySkill').value||u.habilidade_principal===$('#studySkill').value)&&(source!=='favorites'||fav.includes(u.id))&&(source!=='new'||!p[u.id])&&(source!=='due'||p[u.id]&&new Date(p[u.id].nextReview).getTime()<=now)&&($('#studyMode').value!=='pt-en'||paired(u)))}
function updateEligible(){$('#eligibleCount').textContent=`${filtered().length} cartões elegíveis para estes filtros.`}
function renderSummary(){const p=read(progressKey,{}),now=Date.now(),s={new:units.length,learning:0,due:0,mastered:0};for(const r of Object.values(p)){s.new--;if(r.state==='dominated')s.mastered++;else s.learning++;if(new Date(r.nextReview).getTime()<=now)s.due++}const by=LEVELS.map(l=>`${l}: ${units.filter(u=>u.nivel===l&&p[u.id]).length}`).filter(x=>!/\: 0$/.test(x)).join(' · ')||'Nenhum nível estudado';$('#studySummary').innerHTML=`<div><strong>${s.new}</strong><span>Novas</span></div><div><strong>${s.learning}</strong><span>Em aprendizagem</span></div><div><strong>${s.due}</strong><span>A revisar hoje</span></div><div><strong>${s.mastered}</strong><span>Dominadas</span></div><div><strong>${Object.keys(p).length}</strong><span>Total estudado</span></div><p>${by}</p>`}
function bind(){document.querySelectorAll('#studySetup select').forEach(x=>x.onchange=updateEligible);$('#startStudy').onclick=start;$('#resumeStudy').onclick=showSession;$('#endStudy').onclick=end;const back=document.createElement('a');back.className='primary';back.textContent='Voltar ao painel de origem';back.href=new URLSearchParams(location.search).get('origem')||'index.html';$('#studySetup .actions').append(back)}
function start(){const p=read(progressKey,{}),now=Date.now(),e=filtered(),due=e.filter(u=>p[u.id]&&new Date(p[u.id].nextReview).getTime()<=now),rest=e.filter(u=>!due.includes(u)),queue=[...due,...rest].slice(0,+$('#studyLimit').value).map(u=>u.id);if(!queue.length){$('#eligibleCount').textContent='Nenhum cartão elegível. Ajuste os filtros.';return}session={version:1,queue,index:0,completed:0,mode:$('#studyMode').value,origin:new URLSearchParams(location.search).get('origem')||'index.html',startedAt:new Date().toISOString(),revealed:false};write(sessionKey,session);showSession()}
function showSession(){$('#studySetup').hidden=true;$('#studySession').hidden=false;renderCard()}function current(){return units.find(u=>u.id===session.queue[session.index])}
function prompt(u){if(session.mode==='en-pt')return['Leia em inglês e recorde o sentido em português.',u.conteudo_en[0],u.traducoes[0]];if(session.mode==='pt-en')return['Leia em português e recorde a expressão em inglês.',u.traducoes[0],u.conteudo_en[0]];if(session.mode==='concept')return['Recorde exemplos que expressem este conceito.',u.titulo,u.conteudo_en.map((x,i)=>`${x}${u.traducoes[i]?` — ${u.traducoes[i]}`:''}`).join('\n')];return['Leia o conteúdo e faça uma autoavaliação.',u.explicacao_pt,u.conteudo_en.map((x,i)=>`${x}${u.traducoes[i]?` — ${u.traducoes[i]}`:''}`).join('\n')]}
function renderCard(){const u=current();if(!u){finish();return}const q=prompt(u),total=session.queue.length;$('#sessionProgress').textContent=`Cartão ${Math.min(session.completed+1,total)} de ${total} · ${session.completed} avaliados`;$('#studySession .progress i').style.width=`${100*session.completed/Math.max(1,total)}%`;$('#studyCard').innerHTML=`<div><span class="badge">${esc(u.nivel)}</span><span class="badge">${esc(u.habilidade_principal)}</span></div><h2>${esc(u.titulo)}</h2><p class="study-instruction">${esc(q[0])}</p><div class="study-front">${esc(q[1])}</div><div class="study-answer" ${session.revealed?'':'hidden'}><h3>Resposta e conteúdo</h3><p>${esc(q[2]).replace(/\n/g,'<br>')}</p><p>${esc(u.explicacao_pt)}</p><a class="open-unit" href="niveis/${u.nivel.toLowerCase()}/#${u.id}">Abrir unidade completa</a><div class="rating">${[['repeat','Repetir'],['hard','Difícil'],['good','Bom'],['easy','Fácil']].map(x=>`<button data-rating="${x[0]}">${x[1]}</button>`).join('')}</div></div>${session.revealed?'':'<button id="revealStudy" class="primary">Revelar resposta</button>'}`;if(!session.revealed)$('#revealStudy').onclick=()=>{session.revealed=true;write(sessionKey,session);renderCard();setTimeout(()=>$('#studyCard .rating button')?.focus())};document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=()=>rate(b.dataset.rating))}
function rate(rating){const u=current(),all=read(progressKey,{}),old=all[u.id]||{},now=new Date(),base={repeat:1,hard:2,good:5,easy:12}[rating],streak=rating==='repeat'?0:(old.streak||0)+1,mult=rating==='repeat'?1:Math.min(4,1+Math.max(0,streak-1)*.35),reviews=(old.reviews||0)+1;all[u.id]={firstStudy:old.firstStudy||now.toISOString(),lastReview:now.toISOString(),nextReview:new Date(now.getTime()+base*mult*day).toISOString(),reviews,lastRating:rating,streak,state:rating==='repeat'?'learning':rating==='easy'&&streak>=3?'dominated':reviews===1?'learning':'review'};write(progressKey,all);if(rating==='repeat')session.queue.push(u.id);session.completed++;session.index++;session.revealed=false;write(sessionKey,session);renderSummary();renderCard()}
function end(){write(sessionKey,session);$('#studySession').hidden=true;$('#studySetup').hidden=false;$('#resumeStudy').hidden=false}function finish(){localStorage.removeItem(sessionKey);session=null;$('#studyCard').innerHTML='<h2>Sessão concluída</h2><p>As avaliações foram salvas neste dispositivo.</p><a href="index.html">Voltar ao início</a>';$('#sessionProgress').textContent='Sessão concluída';$('#studySession .progress i').style.width='100%';renderSummary()}load();
