import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const raiz = path.resolve(import.meta.dirname, '..'), fonteRaiz = path.resolve(raiz, '..', 'Arquivo_Fonte');
const ler = arquivo => JSON.parse(fs.readFileSync(path.join(raiz, arquivo), 'utf8'));
const triagem = ler('dados/lote-037-triagem.json'), mapa = ler('dados/mapeamento-fontes-extensas-037.json');
const unidades = ['a1', 'a2', 'b1', 'b2', 'c1', 'c2', 'kids'].flatMap(nivel => ler(`dados/${nivel}/unidades.json`));
const atividades = ler('dados/atividades.json'), cobertura = ler('dados/auditoria-cobertura-jornada-037.json'), estabilidade = ler('dados/auditoria-estabilidade-jornada-037.json');
const ids = new Set(unidades.map(unidade => unidade.id)), partes = mapa.fontes.flatMap(fonte => fonte.partes), uteis = partes.filter(parte => parte.decisao.startsWith('consolidar'));
const destinos = parte => [parte.destino_curricular_especifico, ...(parte.destinos_adicionais || [])].filter(Boolean);
const hashes = triagem.sequenciais.every(item => crypto.createHash('sha256').update(fs.readFileSync(path.join(fonteRaiz, item.nome))).digest('hex') === item.hash_bruto);
const fontesNasUnidades = arquivo => unidades.some(unidade => (unidade.fontes || []).some(fonte => fonte.arquivo === arquivo));
const verificacoes = [triagem.intervalo.join(',') === '1217,1218', mapa.fontes.length === 2, mapa.fontes.every(fonte => fonte.leitura_integral), mapa.fontes[0].paginacao.presentes.join(',') === '1,2', mapa.fontes[1].paginacao.blocos_presentes === 4, partes.every(parte => parte.decisao), uteis.every(parte => destinos(parte).every(id => ids.has(id))), mapa.fontes.every(fonte => fonte.totais.uteis_sem_destino === 0), mapa.fontes.every(fonte => !fonte.integridade.corrupcao), partes.every(parte => !parte.elegivel_atividade && !parte.elegivel_jornada), mapa.fontes.every(fonte => fonte.estrutura.imagens_publicadas === 0), !JSON.stringify(mapa).match(/caminho_origem|conteudo_fonte|arquivo_origem|credito_pessoal|[A-Z]:\\\\/i), hashes, fontesNasUnidades(triagem.sequenciais[0].nome), fontesNasUnidades(triagem.sequenciais[1].nome), unidades.length === 834, atividades.length === 1977, ler('dados/subpaineis.json').length === 95, ids.size === 834, new Set(atividades.map(atividade => atividade.id)).size === 1977, cobertura.totais.presentes === 806 && cobertura.totais.complementares === 28, cobertura.orfaos.length === 0 && cobertura.repetidos.length === 0, estabilidade.ids_preservados.length === 806 && !estabilidade.ids_removidos.length, estabilidade.localStorage.progresso_retomada_compativeis && estabilidade.localStorage.favoritos_revisoes_compativeis, ler('dados/auditoria-atividades-037.json').unidades_sem_atividade === 66, triagem.observacao.includes('antes de 1219')];
const nomes = ['intervalo', 'duas fontes', 'leitura integral', 'paginação 1217', 'quatro blocos 1218', 'decisões', 'destinos', 'zero sem destino', 'integridade', 'sem automação', 'zero imagens', 'sanitização', 'hashes', 'procedência 1217', 'procedência 1218', '834 unidades', '1977 atividades', '95 subpainéis', 'IDs unidades', 'IDs atividades', 'Jornada 806+28', 'Jornada íntegra', '806 preservados', 'localStorage', '66 sem atividade', 'encerrado'];
const resultado = {total: verificacoes.length, aprovados: verificacoes.filter(Boolean).length, resultados: verificacoes.map((valor, indice) => ({teste: nomes[indice], resultado: valor ? 'APROVADO' : 'FALHOU'}))};
fs.mkdirSync(path.join(raiz, 'docs/evidencias/lote-037'), {recursive: true});
fs.writeFileSync(path.join(raiz, 'docs/evidencias/lote-037/resultados-validacao-037.json'), `${JSON.stringify(resultado, null, 2)}\n`);
console.log(`LOTE 037: ${resultado.aprovados}/${resultado.total}`);
if (resultado.aprovados !== resultado.total) process.exit(1);
