import fs from 'node:fs';
import path from 'node:path';
const raiz = path.resolve(import.meta.dirname, '..');
const ler = arquivo => JSON.parse(fs.readFileSync(path.join(raiz, arquivo), 'utf8'));
const triagem = ler('dados/lote-029-triagem.json');
const mapa = ler('dados/mapeamento-fontes-extensas-029.json');
const unidades = ['a1', 'a2', 'b1', 'b2', 'c1', 'c2', 'kids'].flatMap(nivel => ler(`dados/${nivel}/unidades.json`));
const atividades = ler('dados/atividades.json');
const cobertura = ler('dados/auditoria-cobertura-jornada-029.json');
const estabilidade = ler('dados/auditoria-estabilidade-jornada-029.json');
const ids = new Set(unidades.map(item => item.id));
const f1197 = mapa.fontes.find(item => item.numero === 1197);
const f1198 = mapa.fontes.find(item => item.numero === 1198);
const f1199 = mapa.fontes.find(item => item.numero === 1199);
const resultados = [];
const testar = (nome, condicao) => { resultados.push({ teste: nome, resultado: condicao ? 'APROVADO' : 'FALHOU' }); if (!condicao) throw new Error(nome); };
testar('intervalo encerrado em 1199', triagem.intervalo.join(',') === '1197,1199');
testar('1197 integral e editorial', f1197.leitura_integral && f1197.decisao_global === 'sem conteúdo didático independente');
testar('1197 9/9 partes decididas', f1197.partes.length === 9 && f1197.partes.every(item => item.decisao));
testar('intermediária 18/18', triagem.validacao_intermediaria.aprovada && triagem.validacao_intermediaria.testes === '18/18');
testar('1198 validada 17/17', triagem.validacao_1198.aprovada && triagem.validacao_1198.testes === '17/17');
testar('1198 36 temas e 191 itens', f1198.secoes.length === 36 && f1198.estrutura.itens_de_tabela === 191);
testar('1199 14 temas', f1199.secoes.length === 14);
testar('1199 150 itens reais', f1199.estrutura.itens_identificados_no_corpo === 150);
testar('divergência 140×150 registrada', f1199.estrutura.itens_declarados_no_cabecalho === 140 && f1199.divergencias[0].identificado === 150);
testar('todas as seções decididas', [...f1198.secoes, ...f1199.secoes].every(item => item.decisao));
testar('todos os destinos existem', [...f1198.secoes, ...f1199.secoes].every(item => ids.has(item.destino_curricular_especifico)));
testar('zero útil sem destino', mapa.fontes.every(item => item.totais.uteis_sem_destino === 0));
testar('sem reprodução extensa', !JSON.stringify(mapa).includes('conteudo_fonte') && !JSON.stringify(mapa).includes('caminho_origem'));
testar('sem atividade automática', [...f1198.secoes, ...f1199.secoes].every(item => !item.elegivel_atividade));
testar('base 834/1977/95', unidades.length === 834 && atividades.length === 1977 && ler('dados/subpaineis.json').length === 95);
testar('IDs de unidades únicos', ids.size === 834);
testar('IDs de atividades únicos', new Set(atividades.map(item => item.id)).size === 1977);
testar('Jornada 806+28', cobertura.totais.presentes === 806 && cobertura.totais.complementares === 28);
testar('Jornada sem órfãos/repetidos', cobertura.orfaos.length === 0 && cobertura.repetidos.length === 0 && cobertura.referencias_inexistentes.length === 0);
testar('806 IDs preservados', estabilidade.ids_preservados.length === 806 && estabilidade.ids_removidos.length === 0);
testar('localStorage preservado', estabilidade.localStorage.progresso_retomada_compativeis && estabilidade.localStorage.favoritos_revisoes_compativeis && !estabilidade.localStorage.formato_alterado);
testar('66 sem atividade', ler('dados/auditoria-atividades-029.json').unidades_sem_atividade === 66);
testar('Kids válido', ler('dados/kids/unidades.json').every(item => item.nivel_cefr));
testar('C2 justificado', ler('dados/c2/unidades.json').every(item => item.justificativa_c2));
const evidencia = { total: resultados.length, aprovados: resultados.filter(item => item.resultado === 'APROVADO').length, resultados };
fs.writeFileSync(path.join(raiz, 'docs/evidencias/lote-029/resultados-validacao-029.json'), `${JSON.stringify(evidencia, null, 2)}\n`);
console.log(`LOTE 029: ${evidencia.aprovados}/${evidencia.total}`);
