import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const raiz = path.resolve(import.meta.dirname, '..');
const fonteRaiz = (process.env.ARQUIVO_FONTE_DIR || path.resolve(import.meta.dirname,'../../Arquivo_Fonte'));
const ler = arquivo => JSON.parse(fs.readFileSync(path.join(raiz, arquivo), 'utf8'));
const unidades = ['a1','a2','b1','b2','c1','c2','kids'].flatMap(n => ler(`dados/${n}/unidades.json`));
const atividades = ler('dados/atividades.json');
const triagem = ler('dados/lote-012-triagem.json');
const rotas = ler('dados/auditoria-rotas-012.json');
const estabilidade = ler('dados/auditoria-estabilidade-jornada-012.json');
const mapa = ler('dados/mapa-fontes.json');
const revisao = ler('dados/revisao-fontes.json');
const resultados = [];
function check(teste, ok, detalhe = '') { resultados.push({ teste, resultado: ok ? 'APROVADO' : 'FALHOU', detalhe }); if (!ok) throw new Error(`${teste}: ${detalhe}`); }
const normal = texto => String(texto||'').toLowerCase().replace(/[.,!?;:]/g,'').replace(/\s+/g,' ').trim();
check('JSONs obrigatórios válidos', ['dados/atividades.json','dados/jornadas.json','dados/lote-012-triagem.json','dados/matriz-curricular-012.json','dados/auditoria-atividades-012.json','dados/auditoria-rotas-012.json'].every(a=>{try{ler(a);return true}catch{return false}}));
check('IDs de unidade únicos', new Set(unidades.map(u=>u.id)).size===unidades.length, `${unidades.length}`);
check('IDs de atividade únicos', new Set(atividades.map(a=>a.id)).size===atividades.length, `${atividades.length}`);
check('fontes sequenciais completas', triagem.sequenciais.length===60&&triagem.sequenciais[0].numero===541&&triagem.sequenciais.at(-1).numero===600);
check('amostragem dirigida completa', triagem.direcionadas.length===17);
check('antecipadas não duplicadas', new Set(triagem.direcionadas.map(x=>x.numero)).size===triagem.direcionadas.length);
check('nenhuma lacuna ambígua publicada', atividades.every(a=>a.tipo!=='completar_lacuna'));
check('pareamentos um a um', atividades.filter(a=>a.tipo==='parear').every(a=>a.resposta.pares.length===a.dados.ingles.length&&a.resposta.pares.length===a.dados.portugues.length&&a.resposta.pares.every(p=>a.dados.ingles.includes(p.en)&&a.dados.portugues.includes(p.pt))));
check('reordenações não triviais', atividades.filter(a=>a.tipo==='reordenar').every(a=>normal(a.resposta.texto).split(' ').length>=3));
check('reordenações preservam tokens e contrações', atividades.filter(a=>a.tipo==='reordenar').every(a=>a.dados.tokens.flatMap(normal).join&&!a.dados.tokens.includes("'")&&!a.dados.tokens.includes('’')));
check('contrastes sem distrator inventado', atividades.filter(a=>a.tipo==='identificar_contraste').every(a=>a.dados.formas.length>=2&&a.resposta.exemplos.length>=2));
check('distribuição de atividades calculável', Math.max(0,...unidades.map(u=>atividades.filter(a=>a.unidade_id===u.id).length))<=10);
check('jornada estável', estabilidade.ids_removidos.length===0&&estabilidade.ids_preservados.length===estabilidade.ids_anteriores.length);
check('Kids com CEFR obrigatório', ler('dados/kids/unidades.json').length>=5&&ler('dados/kids/unidades.json').every(u=>u.nivel_cefr));
check('C2 com justificativa obrigatória', ler('dados/c2/unidades.json').length>=2&&ler('dados/c2/unidades.json').every(u=>u.justificativa_c2));
check('todas as rotas HTTP 200', rotas.length===11&&rotas.every(r=>r.http_status===200));
check('console sem erros', rotas.every(r=>r.erros_console.length===0));
check('progresso anterior continua por ID', fs.readFileSync(path.join(raiz,'js/progresso.js'),'utf8').includes('nivelState')||fs.readFileSync(path.join(raiz,'js/app.js'),'utf8').includes('nivelState'));
check('hashes das fontes preservados', [...triagem.sequenciais,...triagem.direcionadas].every(x=>{const arquivo=path.join(fonteRaiz,x.nome);return fs.existsSync(arquivo)&&crypto.createHash('sha256').update(fs.readFileSync(arquivo)).digest('hex')===x.hash_bruto}));
check('estados da revisão refletidos no mapa', mapa.arquivos.filter(x=>revisao[x.id]).every(x=>x.estado_revisao===revisao[x.id].estado));
const out = path.join(raiz,'docs/evidencias/lote-012/resultados-validacao-012.json');
fs.writeFileSync(out,JSON.stringify({total:resultados.length,aprovados:resultados.filter(x=>x.resultado==='APROVADO').length,resultados},null,2)+'\n');
console.log(`LOTE 012 VALIDAÇÃO OK: ${resultados.length}/${resultados.length}`);
