import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';const raiz=path.resolve(import.meta.dirname,'..'),src=(process.env.ARQUIVO_FONTE_DIR || path.resolve(import.meta.dirname,'../../Arquivo_Fonte')),ns=['a1','a2','b1','b2','c1','c2','kids'];
const ler=a=>JSON.parse(fs.readFileSync(path.join(raiz,a),'utf8')),u=ns.flatMap(n=>ler(`dados/${n}/unidades.json`)),a=ler('dados/atividades.json'),t=ler('dados/lote-014-triagem.json'),r13=ler('dados/auditoria-rendimento-lote013.json'),j=ler('dados/auditoria-estabilidade-jornada-014.json'),s=ler('dados/subpaineis.json'),p=ler('dados/paineis.json'),r=ler('dados/revisao-fontes.json'),m=ler('dados/mapa-fontes.json'),aa=ler('dados/auditoria-atividades-014.json');
const out=[];function ok(nome,cond,det=''){out.push({teste:nome,resultado:cond?'APROVADO':'FALHOU',detalhe:det});if(!cond)throw Error(`${nome}: ${det}`)}
ok('JSONs obrigatórios válidos',true);ok('100 sequenciais completos',t.sequenciais.length===100&&t.sequenciais[0].numero===681&&t.sequenciais.at(-1).numero===780);ok('12 dirigidas únicas',t.direcionadas.length===12&&new Set(t.direcionadas.map(x=>x.numero)).size===12);
ok('auditoria do lote 013 completa',r13.quantidade===92&&r13.fontes.every(x=>x.motivo_sem_nova_unidade||x.unidades_canonicas_relacionadas.length||x.status_anterior.includes('classificada')));
ok('canônicas sem unidade justificadas',t.sequenciais.filter(x=>x.duplicidade==='não duplicada'&&!x.unidades_canonicas_relacionadas.length).every(x=>x.justificativa));ok('procedências anexadas',t.sequenciais.filter(x=>x.numero===681).every(x=>x.unidades_canonicas_relacionadas.length===2));
ok('IDs de unidade únicos',new Set(u.map(x=>x.id)).size===u.length,String(u.length));ok('IDs de atividade únicos',new Set(a.map(x=>x.id)).size===a.length,String(a.length));ok('nenhuma unidade vazia',u.every(x=>x.titulo&&x.conteudo_en?.length&&x.fonte?.arquivo));
const ex=new Map();let dup=false;for(const x of u.filter(x=>x.id.includes('-L14-')))for(const e of x.conteudo_en){const k=String(e).trim().toLowerCase();if(ex.has(k))dup=true;ex.set(k,x.id);}ok('nenhum exemplo L14 exato duplicado',!dup);
ok('painéis válidos',u.every(x=>p.some(y=>y.id===x.paineis[0])));ok('95 subpainéis mantidos',s.length===95,String(s.length));ok('subpainéis novos usam agrupamentos existentes',u.filter(x=>x.id.includes('-L14-')).every(x=>s.some(y=>y.painel===x.paineis[0]&&y.titulo===x.subpainel)));
ok('pré-requisitos sem autorreferência',u.every(x=>!(x.pre_requisitos||[]).includes(x.id)));ok('jornada estável',j.ids_removidos.length===0&&j.ids_preservados.length===j.ids_anteriores.length&&j.ids_adicionados.length===10);ok('sete níveis na jornada',j.niveis_testados.length===7);
ok('atividades novas auditadas',aa.total_unidades_novas===10&&aa.unidades.length===10);ok('atividades novas inequívocas',aa.unidades.every(x=>x.ambiguidades_detectadas.length===0&&x.atividades_criadas.length===1));ok('sem completar lacuna',a.every(x=>x.tipo!=='completar_lacuna'));
ok('Kids com CEFR',ler('dados/kids/unidades.json').every(x=>x.nivel_cefr));ok('C2 com justificativa',ler('dados/c2/unidades.json').every(x=>x.justificativa_c2));
ok('hashes das fontes preservados',[...t.sequenciais,...t.direcionadas].every(x=>{const q=path.join(src,x.nome);return fs.existsSync(q)&&crypto.createHash('sha256').update(fs.readFileSync(q)).digest('hex')===x.hash_bruto}));ok('mapa reflete revisão',m.arquivos.filter(x=>r[x.id]).every(x=>x.estado_revisao===r[x.id].estado));
ok('antecipadas não reprocessadas',t.antecipadas_ja_concluidas.length===0);const prog=fs.readFileSync(path.join(raiz,'docs/PROGRESSO.md'),'utf8');ok('progresso automático único',(prog.match(/<!-- ESTADO-ATUAL:INICIO -->/g)||[]).length===1&&!/^## Retomada$/m.test(prog));
const payload={total:out.length,aprovados:out.filter(x=>x.resultado==='APROVADO').length,resultados:out};fs.mkdirSync(path.join(raiz,'docs/evidencias/lote-014'),{recursive:true});fs.writeFileSync(path.join(raiz,'docs/evidencias/lote-014/resultados-validacao-014.json'),JSON.stringify(payload,null,2)+'\n');console.log(`LOTE 014: ${payload.aprovados}/${payload.total}`);
